### ISSUE TITLE
Request: cancellation options on the drag-n-drop with directions setting.

### ISSUE THREAD

**Issue by ky7245** [universeroc/super-drag#11]
Hello! This is a wounderful extension!
I can't live without it. And there is one feature I would like to see added.
I would like to see a cancel (or do nothing) option added to the drag-n-drop with directions setting.
It would be very nice to be able to cancel when I drag by mistake.
Also, having the option would make it possible to super-drag only in certain directions.

Thank you in advance for your consideration.
Best Regards.

**Comment by zhoujy0915** [comment]
如何设置搜索引擎，没有弹框提示设置引擎

**Comment by universeroc** [comment]
> Hello! This is a wounderful extension! I can't live without it. And there is one feature I would like to see added. I would like to see a cancel (or do nothing) option added to the drag-n-drop with directions setting. It would be very nice to be able to cancel when I drag by mistake. Also, having the option would make it possible to super-drag only in certain directions.
> 
> Thank you in advance for your consideration. Best Regards.

You can press the "ESC" button to cancel a drag-n-drop action, this is the classical action in any similar scene. :)

**Comment by universeroc** [comment]
> 如何设置搜索引擎，没有弹框提示设置引擎

可以在扩展栏图标点击弹出的设置框上，选择拖拽使用的搜索引擎，目前都是内置的，可以直接选择，有反馈需要自定义的，规划中
