### ISSUE TITLE
能增加，自动判断，在当前网站中搜索选中文本，直接谷歌站内搜索么？  

### ISSUE THREAD

**Issue by yangchen158158** [universeroc/super-drag#13]
能增加，自动判断，在当前网站中搜索选中文本，直接谷歌站内搜索么？

**Comment by universeroc** [comment]
是直接用站内搜索而不是用搜索引擎全网搜索是这种场景么？

**Comment by yangchen158158** [comment]
> 是直接用站内搜索而不是用搜索引擎全网搜索是这种场景么？

对对，很多论坛网页自带的搜索框，效果很差，如果能谷歌站内搜索  百度站内搜索这样，方便极了

**Comment by yangchen158158** [comment]
> > > 是直接用站内搜索而不是用搜索引擎全网搜索是这种场景么？
> > 
> > 
> > 对对，很多论坛网页自带的搜索框，效果很差，如果能谷歌站内搜索 百度站内搜索这样，方便极了
> 
> 听起来不错，能不能帮忙多描述一下功能的细节，比如是否需要一些设置项，来设置哪些启用站内搜索哪些不启用？还有没有其他的

百分浏览器。猫眼浏览器。这些自带的超级拖拽 这样的站内搜索功能
就是选中文字，然后拖拽 ，就直接搜索这个当前网页的站内搜索。
![image](https://github.com/universeroc/super-drag/assets/62718910/1fb4e9cd-2609-4538-958e-9d4f06e0d687)
![image](https://github.com/universeroc/super-drag/assets/62718910/7d44889a-66ef-42d2-9448-c5617eeaf4d9)

**Comment by universeroc** [comment]
> > > > 是直接用站内搜索而不是用搜索引擎全网搜索是这种场景么？
> > > 
> > > 
> > > 对对，很多论坛网页自带的搜索框，效果很差，如果能谷歌站内搜索 百度站内搜索这样，方便极了
> > 
> > 
> > 听起来不错，能不能帮忙多描述一下功能的细节，比如是否需要一些设置项，来设置哪些启用站内搜索哪些不启用？还有没有其他的
> 
> 百分浏览器。猫眼浏览器。这些自带的超级拖拽 这样的站内搜索功能 就是选中文字，然后拖拽 ，就直接搜索这个当前网页的站内搜索。 ![image](https://private-user-images.githubusercontent.com/62718910/292978470-1fb4e9cd-2609-4538-958e-9d4f06e0d687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjEzNTUsIm5iZiI6MTcwMzY2MTA1NSwicGF0aCI6Ii82MjcxODkxMC8yOTI5Nzg0NzAtMWZiNGU5Y2QtMjYwOS00NTM4LTk1OGUtOWQ0ZjA2ZTBkNjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMTJhNWFiMjI3ZTIwMDU1YzA0YTMxM2YzNmEyZjU3MDliMmRmM2EyZjJjY2RiZDI5MjQ2MDU0Nzc1MzI0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._jABvkadsQkhptrwrZi2qhc4kOYKOk8J56HL6rFRkN8) ![image](https://private-user-images.githubusercontent.com/62718910/292978491-7d44889a-66ef-42d2-9448-c5617eeaf4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjEzNTUsIm5iZiI6MTcwMzY2MTA1NSwicGF0aCI6Ii82MjcxODkxMC8yOTI5Nzg0OTEtN2Q0NDg4OWEtNjZlZi00MmQyLTk0NDgtYzU2MTdlZWFmNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDA3MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OWMxZTlhOGNiMGZlMmMzNjI1ZWNlNWViODU0NjEzYzMwMGY3ZDEzZGUyYTUxNmE3NDM2NTljOGY3NjJlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AGjWjCMhGnIuYjT42GfDO1ztJGY6mo13rZgZ3-ylraQ)

好的，真棒，我规划一下看看在近期哪个版本加入一下 :)

**Comment by universeroc** [comment]
已经在 0.9.9 版本实现，已提交审核，通过后升级即可支持

<img width="335" alt="Screenshot 2024-08-23 at 11 30 37 AM" src="https://github.com/user-attachments/assets/e5ade7b9-f436-4041-b952-8a2c68e14b62">

在选项里可以设置打开
