### ISSUE TITLE
b站热门页面 动态无法拖拽

### ISSUE THREAD

**Issue by knItalian** [universeroc/super-drag#16]
在首页 动态 视频等页面 弹出的动态列表都可以拖拽 
但唯独热门页面 动态里的内容无法拖拽 

![5](https://github.com/universeroc/super-drag/assets/32791144/acd24fe8-036b-4aa0-bfef-2dbbc0dddef9)

https://www.bilibili.com/v/popular/all/

**Comment by universeroc** [comment]
@knItalian  我按照你说的网页，和操作试过没有复现，具体看我录制的视频

https://github.com/universeroc/super-drag/assets/3518853/8a4251b6-cf72-4d39-bf44-b7bea28dea28
