### ISSUE TITLE
不同方向是否能单独设置前后台打开方式？

### ISSUE THREAD

**Issue by WYithal** [universeroc/super-drag#17]
目前好像是四个方向统一设置的，或者需要按ctrl控制，希望每个拖拽方向能单独控制前后台打开方式

**Comment by universeroc** [comment]
> 目前好像是四个方向统一设置的，或者需要按ctrl控制，希望每个拖拽方向能单独控制前后台打开方式

前后台目前确实是同一设置的，暂无独立配置计划哈

**Comment by docker-master** [comment]
哈哈我也在找这个，竟然不支持，只好用别的了
