### ISSUE TITLE
Opening unwanted GitHub tab when starting the browser

### ISSUE THREAD

**Issue by regic** [universeroc/super-drag#2]
Hey,

I really appreciate your hard work, and the extension works great!
However, opening an unwanted GitHub tab when I open the browser is not the experience I expect. In this case, I would rather uninstall the extension rather than continue using it with this unexpected (and unwanted) behavior...
So is it possible to remove this page, it could easily be added as a prominent link in the plugin options. Or at least add an option to stop this behavior.

Thanks in advance!

**Comment by universeroc** [comment]
sorry for that already removed as I want to use github issues to track all users' feedback so as to quick to improve
