### ISSUE TITLE
Ecosia搜索链接错误

### ISSUE THREAD

**Issue by xjzh123** [universeroc/super-drag#3]
用ecosia搜索，会打开ecosia.org/searchXXXXX，XXXXX为搜索词，直接跳转到首页了。应为https://www.ecosia.org/search?q=XXXXX

**Comment by universeroc** [comment]
> 用ecosia搜索，会打开ecosia.org/searchXXXXX，XXXXX为搜索词，直接跳转到首页了。应为https://www.ecosia.org/search?q=XXXXX

收到，抱歉回复完了，近期会修复上线

**Comment by universeroc** [comment]
fixed at 0.9.1 already in publishing process
