### ISSUE TITLE
<> 没有正确处理

### ISSUE THREAD

**Issue by arix00** [universeroc/super-drag#4]
比如
`#include <windows.h>`

如果拖拽全部，则只搜了 `#include`
单`<windows.h>`就什么都没有

直接拖到chrome的新tab是正常的

**Comment by universeroc** [comment]
> 比如 `#include <windows.h>`
> 
> 如果拖拽全部，则只搜了 `#include` 单`<windows.h>`就什么都没有
> 
> 直接拖到chrome的新tab是正常的

收到，会近期修复上线，感谢反馈

**Comment by universeroc** [comment]
fixed at 0.9.1 already in publishing process
