### ISSUE TITLE
URL blacklist有时会失效

### ISSUE THREAD

**Issue by halw001** [universeroc/super-drag#6]
![1](https://user-images.githubusercontent.com/23332715/222739620-2bb8564d-deed-48a3-8e42-ffa50daccbaf.png)
已经把discord.com添加到禁用列表里，刚开始是有效的，等过了几天就失效了，得重新刷新一下网页才能重新生效。这个问题已经出现过好几次

**Comment by universeroc** [comment]
> ![1](https://user-images.githubusercontent.com/23332715/222739620-2bb8564d-deed-48a3-8e42-ffa50daccbaf.png) 已经把discord.com添加到禁用列表里，刚开始是有效的，等过了几天就失效了，得重新刷新一下网页才能重新生效。这个问题已经出现过好几次

感谢反馈，我按照这个测试一下，会在下个版本修复

**Comment by universeroc** [comment]
fixed at 0.9.1 already in publishing process
