### ISSUE TITLE
0.9.1版拖拽会出现多个窗口

### ISSUE THREAD

**Issue by arix00** [universeroc/super-drag#7]
有时候2个有时候3个
之前版本正常

chrome 112

发现：和页面有关，有些页面拖拽正常
有些页面，比如当前这个issue，拖拽就会开多窗口

**Comment by Marce1ek** [comment]
遇到了一样的问题

**Comment by universeroc** [comment]
@Marce1ek 具体页面URL 有不提供个
@arix00 我先看看issue页面

**Comment by universeroc** [comment]
OK, 我复现这个问题了，已经发布等审核 0.9.2
