### ISSUE TITLE
Extension won't work in MacOS - Edge / Chrome

### ISSUE THREAD

**Issue by kladskjasd** [universeroc/super-drag#8]
Hi @universeroc . First of, thanks for your work in developing the extension. I have been using in Windows 11 with no issue, but I recently purchased a Macbook, and I have discovered that, sadly, the extension won't work here. I have tried in different Chromium-based browsers (Edge, Edge Dev, Chrome, Brave), and the problem remains the same. 

Dragged links move, leaving a kind of a shadow, but not opening, while dragged text, when I try to drag, gets de-selected. I am convinced this is a Chromium issue particular to MacOS, as I have been using similar extensions on Firefox in MacOS with no problems at all. I have also tried similar extensions for Chrome, and they all suffer from the same issue. 

I'm attaching a screen recording reproducing both behaviours in case it helps you find the issue. 

https://github.com/universeroc/super-drag/assets/96435418/9285995d-c2e4-4fc5-a433-ef9bd70883e2

Thanks for your time!

**Comment by universeroc** [comment]
Ok, I'm checking it out and reply you later. Thanks for your feedback.



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 19, 2023 17:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [universeroc/super-drag] Extension won't work in MacOS - Edge /Chrome (Issue #8)




 
Hi @universeroc . First of, thanks for your work in developing the extension. I have been using in Windows 11 with no issue, but I recently purchased a Macbook, and I have discovered that, sadly, the extension won't work here. I have tried in different Chromium-based browsers (Edge, Edge Dev, Chrome, Brave), and the problem remains the same.
 
Dragged links move, leaving a kind of a shadow, but not opening, while dragged text, when I try to drag, gets de-selected. I am convinced this is a Chromium issue particular to MacOS, as I have been using similar extensions on Firefox in MacOS with no problems at all. I have also tried similar extensions for Chrome, and they all suffer from the same issue.
 
I'm attaching a screen recording reproducing both behaviours in case it helps you find the issue.
 
https://github.com/universeroc/super-drag/assets/96435418/9285995d-c2e4-4fc5-a433-ef9bd70883e2
 
Thanks for your time!

**Comment by kladskjasd** [comment]
Just another one here, I was testing it again, and the link dragging does works, so I think the issue is concentrated on the text selection and dragging.

**Comment by universeroc** [comment]
Ok, thanks for your further feedback



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 19, 2023 18:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [universeroc/super-drag] Extension won't work in MacOS - Edge /Chrome (Issue #8)




 
Just another one here, I was testing it again, and the link dragging does works, so I think the issue is concentrated on the text selection and dragging.

**Comment by universeroc** [comment]
Sorry for late reply as I'm busy about my job recently.
I've reproduced your issue, and find a solution: maybe only when you drag start you can only make a little change is to hold on a small duration just before you start dragging, you can check my screenshot for extra explaination.

Yeah it's a good user experience to use and I'm also trying to find out a better way to solve this issue.


https://github.com/universeroc/super-drag/assets/3518853/4fc71cb3-afb5-4089-b72f-c4e0d8502158
