### ISSUE TITLE
Deprecation warning in superdrag.js

### ISSUE THREAD

**Issue by grandgeorg** [universeroc/super-drag#9]
Hi,
there is a deprecation warning in superdrag.js:

superdrag.js:134 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by DEAN-Cherry** [comment]
![image](https://github.com/universeroc/super-drag/assets/76607677/d8b5db49-7220-4c83-94d9-7178f9fd5bfe)
Yes, hope this can be fixed

**Comment by universeroc** [comment]
yes, I've gotten this warning, the next version will fix it. Thanks @grandgeorg @DEAN-Cherry :)

**Comment by hfdem** [comment]
`superdrag.js:134 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.`

**Comment by universeroc** [comment]
> `superdrag.js:134 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.`

sorry a bit late, next version fix it :P

**Comment by universeroc** [comment]
fixed at 0.9.8, it's released after google's review
